name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            runtime-id: osx-x64
          - os: windows-latest
            runtime-id: win-x64
          - os: ubuntu-latest
            runtime-id: linux-x64
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    # We need net5 + net6 or we fail on testing
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore TinyUpdate.sln
    - name: Build
      run: dotnet build TinyUpdate.sln --no-restore
    - name: Test
      run: dotnet test TinyUpdate.sln --no-build --verbosity normal --runtime ${{ matrix.runtime-id }}
